package app.aegis.data.local

import androidx.room.Room
import androidx.room.RoomDatabase
import platform.Foundation.NSHomeDirectory

fun getDatabaseBuilder(): RoomDatabase.Builder<AegisDatabase> {
    val dbFilePath = NSHomeDirectory() + "/aegis.db"
    return Room.databaseBuilder<AegisDatabase>(
        name = dbFilePath,
        factory = { AegisDatabaseConstructor.initialize() }
    )
}
// Note: Room KMP on iOS usually requires `instantiateImpl` if using the KSP generated code directly? 
// Actually current Room EAP documentation says:
// Room.databaseBuilder<MyDatabase>(name = path)
// But on Native we might need to provide the factory if reflection is limited? 
// With KSP, it generates a `MyDatabase_Impl`. 
// Wait, libraries use `factory = { MyDatabase::class.instantiateImpl() }` isn't standard?
// Room 2.7.0-alpha: `Room.databaseBuilder<AppDatabase>(name = dbFilePath)` should work if setup correctly?
// Check updated docs for "Room KMP". 
// Usually: `Room.databaseBuilder<AppDatabase>(name = path)` matches commonMain? No commonMain doesn't have it.
// Platform specific `Room.databaseBuilder`...
// On iOS `instantiateImpl` is often needed because of no reflection.
// Let's assume standard KMP Room setup: `Room.databaseBuilder<AegisDatabase>(name = dbFilePath)`
// But wait, `AegisDatabase` is abstract.
// Error: "Cannot use T as reified type parameter".
// `Room.databaseBuilder` is inline reified? 
// Yes.
// So:
/*
fun getDatabaseBuilder(): RoomDatabase.Builder<AegisDatabase> {
    val dbFilePath = NSHomeDirectory() + "/aegis.db"
    return Room.databaseBuilder<AegisDatabase>(
        name = dbFilePath,
        factory =  { AegisDatabase::class.instantiateImpl() } // This is how some KMP samples show it
    )
}
*/
// But `instantiateImpl()` is generated by KSP. I need to be sure it's accessible.
// I will try to use the simple version first, and if it fails (unresolved reference), I'll fix.
// Actually, `instantiateImpl()` is not a standard method on the class. KSP generates `AegisDatabase_Impl`. 
// So `factory = { AegisDatabase_Impl() }`? But `_Impl` is internal?
// Let's try the simple `Room.databaseBuilder<AegisDatabase>(name = dbFilePath)` first.
